trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  paths:
    include:
    - '*'
    exclude:
    - '*.md'
    - /ActivityReservation.Clients/

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: '$(Build.BuildNumber)'
  latestImageName: '$(dockerId)/activityreservation:latest'
  imageName: '$(dockerId)/activityreservation:$(tagName)'

steps:

- script: dotnet build -c Release
  displayName: 'dotnet build'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: docker tag $(imageName) $(latestImageName)
  displayName: 'Docker tag latest'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
    docker push $(latestImageName)
  displayName: 'Push docker image'
  displayName: 'aaa'
  displayName: 'bbb'
  displayName: 'ccc'
